-- SaaS foundation. Run against PostgreSQL before migrating tenant data.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS tenants (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, slug text UNIQUE NOT NULL, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS tenant_members (tenant_id uuid REFERENCES tenants(id) ON DELETE CASCADE, user_id integer NOT NULL, role text NOT NULL CHECK (role IN ('owner','admin','cashier')), PRIMARY KEY (tenant_id,user_id));
CREATE TABLE IF NOT EXISTS plans (id text PRIMARY KEY, name text NOT NULL, monthly_satang bigint NOT NULL, branch_limit integer NOT NULL, user_limit integer NOT NULL);
CREATE TABLE IF NOT EXISTS subscriptions (tenant_id uuid PRIMARY KEY REFERENCES tenants(id) ON DELETE CASCADE, plan_id text REFERENCES plans(id), provider text, provider_subscription_id text UNIQUE, status text NOT NULL, current_period_end timestamptz);
-- Every business table must carry tenant_id and enforce it through the request transaction.
CREATE INDEX IF NOT EXISTS tenant_members_user_idx ON tenant_members(user_id);

CREATE TABLE IF NOT EXISTS tenant_users (tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, user_id integer NOT NULL, name text NOT NULL, email text NOT NULL, password_hash text NOT NULL, role text NOT NULL CHECK (role IN ('admin','cashier')), status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (tenant_id,user_id), UNIQUE (tenant_id,email));
CREATE TABLE IF NOT EXISTS tenant_sessions (tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, token_hash text PRIMARY KEY, user_id integer NOT NULL, expires timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS tenant_settings (tenant_id uuid PRIMARY KEY REFERENCES tenants(id) ON DELETE CASCADE, shop_name text NOT NULL DEFAULT 'Baan Store', tax_rate numeric NOT NULL DEFAULT 7, receipt_footer text NOT NULL DEFAULT 'ขอบคุณที่อุดหนุน แล้วพบกันใหม่', updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS tenant_categories (tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, id bigint GENERATED ALWAYS AS IDENTITY, name text NOT NULL, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (tenant_id,id), UNIQUE (tenant_id,name));
CREATE TABLE IF NOT EXISTS tenant_products (tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, id bigint GENERATED ALWAYS AS IDENTITY, category_id bigint, sku text NOT NULL, barcode text, name text NOT NULL, cost_price bigint NOT NULL CHECK (cost_price >= 0), sale_price bigint NOT NULL CHECK (sale_price >= 0), stock_qty integer NOT NULL DEFAULT 0 CHECK (stock_qty >= 0), min_stock integer NOT NULL DEFAULT 5, image_url text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (tenant_id,id), UNIQUE (tenant_id,sku), UNIQUE (tenant_id,barcode), FOREIGN KEY (tenant_id,category_id) REFERENCES tenant_categories(tenant_id,id));
CREATE TABLE IF NOT EXISTS tenant_customers (tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, id bigint GENERATED ALWAYS AS IDENTITY, name text NOT NULL, phone text NOT NULL DEFAULT '', email text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (tenant_id,id));
CREATE TABLE IF NOT EXISTS tenant_orders (tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, id bigint GENERATED ALWAYS AS IDENTITY, order_no text NOT NULL, cashier_id integer NOT NULL, customer_id bigint, subtotal bigint NOT NULL, discount bigint NOT NULL, tax bigint NOT NULL, total bigint NOT NULL, payment_status text NOT NULL, order_status text NOT NULL, request_key uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (tenant_id,id), UNIQUE (tenant_id,order_no), UNIQUE (tenant_id,request_key));
ALTER TABLE tenant_orders ADD COLUMN IF NOT EXISTS tax_invoice_no text;
CREATE TABLE IF NOT EXISTS tenant_order_items (tenant_id uuid NOT NULL, id bigint GENERATED ALWAYS AS IDENTITY, order_id bigint NOT NULL, product_id bigint NOT NULL, name text NOT NULL, quantity integer NOT NULL CHECK (quantity > 0), unit_price bigint NOT NULL, cost_price bigint NOT NULL, line_total bigint NOT NULL, PRIMARY KEY (tenant_id,id), FOREIGN KEY (tenant_id,order_id) REFERENCES tenant_orders(tenant_id,id), FOREIGN KEY (tenant_id,product_id) REFERENCES tenant_products(tenant_id,id));
CREATE TABLE IF NOT EXISTS tenant_payments (tenant_id uuid NOT NULL, id bigint GENERATED ALWAYS AS IDENTITY, order_id bigint NOT NULL, method text NOT NULL, amount bigint NOT NULL, tendered bigint NOT NULL, status text NOT NULL, reference text, paid_at timestamptz DEFAULT now(), PRIMARY KEY (tenant_id,id), FOREIGN KEY (tenant_id,order_id) REFERENCES tenant_orders(tenant_id,id));
ALTER TABLE tenant_payments ADD COLUMN IF NOT EXISTS expires_at timestamptz;
CREATE TABLE IF NOT EXISTS tenant_payment_events (tenant_id uuid NOT NULL, event_id text NOT NULL, payment_id bigint, status text NOT NULL, payload jsonb NOT NULL DEFAULT '{}', received_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (tenant_id,event_id));
CREATE TABLE IF NOT EXISTS tenant_stock_movements (tenant_id uuid NOT NULL, id bigint GENERATED ALWAYS AS IDENTITY, product_id bigint NOT NULL, type text NOT NULL, quantity integer NOT NULL, reference_id bigint, note text, created_by integer NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (tenant_id,id), FOREIGN KEY (tenant_id,product_id) REFERENCES tenant_products(tenant_id,id));
CREATE TABLE IF NOT EXISTS tenant_audit_logs (tenant_id uuid NOT NULL, id bigint GENERATED ALWAYS AS IDENTITY, user_id integer NOT NULL, action text NOT NULL, entity_type text, entity_id bigint, metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (tenant_id,id));

CREATE INDEX IF NOT EXISTS tenant_products_stock_idx ON tenant_products(tenant_id,stock_qty);
CREATE INDEX IF NOT EXISTS tenant_orders_created_idx ON tenant_orders(tenant_id,created_at);

-- RLS is enabled as a second boundary. API transactions must SET LOCAL app.tenant_id.
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['tenant_users','tenant_sessions','tenant_settings','tenant_categories','tenant_products','tenant_customers','tenant_orders','tenant_order_items','tenant_payments','tenant_payment_events','tenant_stock_movements','tenant_audit_logs'] LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',t); EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %I',t); EXECUTE format('CREATE POLICY tenant_isolation ON %I USING (tenant_id = current_setting(''app.tenant_id'', true)::uuid) WITH CHECK (tenant_id = current_setting(''app.tenant_id'', true)::uuid)',t); END LOOP; END $$;
