import {all,get,run,transaction,audit} from './db.js';
export class AppError extends Error{constructor(message,status=400,code='VALIDATION_ERROR'){super(message);this.status=status;this.code=code;}}
export function receipt(id){const order=get('SELECT o.*,u.name cashier_name,c.name customer_name FROM orders o JOIN users u ON u.id=o.cashier_id LEFT JOIN customers c ON c.id=o.customer_id WHERE o.id=?',id);if(!order)throw new AppError('ไม่พบออเดอร์',404);return {...order,items:all('SELECT * FROM order_items WHERE order_id=?',id),payments:all('SELECT * FROM payments WHERE order_id=?',id),shop:get('SELECT * FROM settings WHERE id=1')};}
export function checkout(input,user){return transaction(()=>{
 const previous=get('SELECT id,cashier_id FROM orders WHERE request_key=?',input.request_key);
 if(previous){if(previous.cashier_id!==user.id)throw new AppError('รหัสรายการซ้ำ',409);return receipt(previous.id);}
 if(input.customer_id&&!get('SELECT id FROM customers WHERE id=?',input.customer_id))throw new AppError('ไม่พบลูกค้า');
 const seen=new Set();let subtotal=0;
 const lines=input.items.map(item=>{if(seen.has(item.product_id))throw new AppError('สินค้าในตะกร้าซ้ำ');seen.add(item.product_id);const p=get('SELECT * FROM products WHERE id=?',item.product_id);if(!p||p.status!=='active')throw new AppError('สินค้านี้ไม่พร้อมจำหน่าย');if(p.stock_qty<item.quantity)throw new AppError(`${p.name} มีสินค้าเหลือ ${p.stock_qty} ชิ้น`,409,'INSUFFICIENT_STOCK');if(item.expected_price!==p.sale_price)throw new AppError(`ราคา ${p.name} เปลี่ยนแล้ว กรุณาโหลดสินค้าใหม่`,409,'PRICE_CHANGED');subtotal+=p.sale_price*item.quantity;return {...p,quantity:item.quantity};});
 if(input.discount>subtotal)throw new AppError('ส่วนลดต้องไม่เกินยอดสินค้า');
 const tax=Math.round((subtotal-input.discount)*get('SELECT tax_rate FROM settings WHERE id=1').tax_rate/100);const total=subtotal-input.discount+tax;
 if(input.payment_status==='failed')throw new AppError('จำลองการชำระเงินล้มเหลว ไม่มีการสร้างออเดอร์หรือตัดสต็อก',402,'PAYMENT_FAILED');
 if(input.method==='cash'&&input.payment_status==='paid'&&input.tendered<total)throw new AppError('เงินสดที่รับไม่เพียงพอ');
 const orderNo=`BN-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${crypto.randomUUID().slice(0,8).toUpperCase()}`;
 const id=Number(run('INSERT INTO orders(order_no,cashier_id,customer_id,subtotal,discount,tax,total,payment_status,order_status,request_key) VALUES(?,?,?,?,?,?,?,?,?,?)',orderNo,user.id,input.customer_id||null,subtotal,input.discount,tax,total,input.payment_status,'completed',input.request_key).lastInsertRowid);
 for(const p of lines){run('INSERT INTO order_items(order_id,product_id,name,quantity,unit_price,cost_price,line_total) VALUES(?,?,?,?,?,?,?)',id,p.id,p.name,p.quantity,p.sale_price,p.cost_price,p.sale_price*p.quantity);run('UPDATE products SET stock_qty=stock_qty-?,updated_at=CURRENT_TIMESTAMP WHERE id=?',p.quantity,p.id);run('INSERT INTO stock_movements(product_id,type,quantity,reference_id,note,created_by) VALUES(?,?,?,?,?,?)',p.id,'sale',-p.quantity,id,'ขายสินค้า',user.id);}
 run('INSERT INTO payments(order_id,method,amount,tendered,status,reference) VALUES(?,?,?,?,?,?)',id,input.method,total,input.method==='cash'?input.tendered:total,input.payment_status,input.method==='transfer'?'DEMO TRANSFER':null);
 audit(user.id,'checkout','orders',id,{total,status:input.payment_status});return receipt(id);
});}
export function cancelOrder(id,user){return transaction(()=>{const order=receipt(id);if(order.order_status==='cancelled')throw new AppError('ออเดอร์นี้ถูกยกเลิกแล้ว',409);for(const p of order.items){run('UPDATE products SET stock_qty=stock_qty+? WHERE id=?',p.quantity,p.product_id);run('INSERT INTO stock_movements(product_id,type,quantity,reference_id,note,created_by) VALUES(?,?,?,?,?,?)',p.product_id,'return',p.quantity,id,'คืนสต็อกจากการยกเลิก',user.id);}run("UPDATE orders SET order_status='cancelled',payment_status=CASE WHEN payment_status='paid' THEN 'refunded' ELSE 'cancelled' END WHERE id=?",id);run("UPDATE payments SET status=CASE WHEN status='paid' THEN 'refunded' ELSE 'cancelled' END WHERE order_id=?",id);audit(user.id,'cancel','orders',id);return receipt(id);});}
